spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      authentication-database: ${MONGODB_AUTH:admin}
  servlet:
    multipart:
      enabled: true
#      max-file: 10MB
#      request-size: 10MB
server:
   port: ${SERVER_PORT:8080}
#springdoc:
#  swagger-ui:
#    enabled: true